import {
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  Cloudy,
} from "lucide-react";

export const WeatherCodes = {
  200: { description: "Thunderstorm with light rain", icon: null },
  201: { description: "Thunderstorm with rain", icon: null },
  202: { description: "Thunderstorm with heavy rain", icon: null },
  230: { description: "Thunderstorm with light drizzle", icon: null },
  231: { description: "Thunderstorm with drizzle", icon: null },
  232: { description: "Thunderstorm with heavy drizzle", icon: null },
  233: { description: "Thunderstorm with Hail", icon: null },
  300: { description: "Light Drizzle", icon: null },
  301: { description: "Drizzle", icon: null },
  302: { description: "Heavy Drizzle", icon: null },
  500: { description: "Light Rain", icon: null },
  501: { description: "Moderate Rain", icon: null },
  502: { description: "Heavy Rain", icon: null },
  511: { description: "Freezing rain", icon: null },
  520: { description: "Light shower rain", icon: null },
  521: { description: "Shower rain", icon: null },
  522: { description: "Heavy shower rain", icon: null },
  600: { description: "Light snow", icon: null },
  601: { description: "Snow", icon: null },
  602: { description: "Heavy Snow", icon: null },
  610: { description: "Mix snow/rain", icon: null },
  611: { description: "Sleet", icon: null },
  612: { description: "Heavy sleet", icon: null },
  621: { description: "Snow shower", icon: null },
  622: { description: "Heavy snow shower", icon: null },
  623: { description: "Flurries", icon: null },
  700: { description: "Mist", icon: null },
  711: { description: "Smoke", icon: null },
  721: { description: "Haze", icon: null },
  731: { description: "Sand/dust", icon: null },
  741: { description: "Fog", icon: null },
  751: { description: "Freezing Fog", icon: null },
  800: { description: "Clear sky", icon: null },
  801: { description: "Few clouds", icon: null },
  802: { description: "Scattered clouds", icon: null },
  803: { description: "Broken clouds", icon: null },
  804: { description: "Overcast clouds", icon: null },
  900: { description: "Unknown Precipitation", icon: null },
};
